version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: renegatemaster/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media
  frontend:
    image: renegatemaster/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  infra:
    image: renegatemaster/foodgram_infra
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/app/media
    ports:
      - 8080:80
