version: '3.7'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - /var/foodgram/postgres-data:/var/lib/postgresql/data
    restart: always
  backend:
    image: renegatemaster/foodgram_backend
    env_file: .env
    volumes:
      - /var/foodgram/files/static:/backend_static
      - /var/foodgram/files/media:/app/media
  frontend:
    image: renegatemaster/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - /var/foodgram/files/static:/frontend_static
  infra:
    image: renegatemaster/foodgram_infra
    env_file: .env
    volumes:
      - /var/foodgram/files/static:/static
      - /var/foodgram/files/media:/app/media
    ports:
      - 8000:80
