# Generated by Django 3.2.3 on 2023-07-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230728_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientinrecipe',
            old_name='quantity',
            new_name='amount',
        ),
    ]
